name: leadgram2
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter
  razorpay_flutter: 1.1.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  flutter_local_notifications: ^1.3.0
  image_picker:
  cloud_firestore:
  page_indicator:
  pin_code_fields:
  grouped_buttons:
  firebase_auth:
  autocomplete_textfield: ^1.7.3
  auto_size_text:
  firebase_storage:
  file_picker: ^1.9.0+1
  cloud_functions: ^0.5.0
  toast: ^0.1.5
  firebase_messaging:
  firebase_dynamic_links:
  share: ^0.6.4+3
  badges: ^1.1.1
  intl: ^0.15.8
  google_sign_in: ^4.5.4
  firebase_core:
  flutter_signin_button: ^1.1.0
  progress_dialog: ^1.1.0+1
  package_info: 0.4.3
  firebase_remote_config:
  url_launcher: 5.7.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/
    - assets/Logo/
    - assets/Intro/
    - assets/BANNER/
    - assets/pages/

